spring:  
  application:  
    name: User  
server:  
  port: 18082   
eureka:
  client:   
    service-url:   
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.user.entity